### ISSUE TITLE
终于有个中文社区了

### ISSUE THREAD

**Issue by shiling02404** [dapr-cn/dapr-cn-site#8]
我们也正在用dapr,也发现还有不少的问题，不过迭代速度还挺快。
前期给dapr官方提交的一些代码也合入到主干在1.8发布了（解决使用consul做名字解析服务时的负载问题https://github.com/dapr/components-contrib/pull/1802).

发现目前内地使用dapr的并不多，生产环境使用的更少，还是看好未来的发展，有时间可以一起交流

**Comment by ElderJames** [comment]
欢迎加群交流

**Comment by shiling02404** [comment]
哪个群
